
sudo: false

language: java
jdk:
  - oraclejdk8

  
before_script:  
  - mysql -u root -e  'CREATE DATABASE db_example; '
  - mysql -u root -e  "CREATE USER 'tutorialuser'@'localhost' IDENTIFIED BY 'tutorialmy5ql';"
  - mysql -u root -e  "GRANT ALL PRIVILEGES ON *.* TO 'tutorialuser'@'localhost';"
  - mysql -u root -e  'FLUSH PRIVILEGES;'

install: /bin/true

script:
  # pending: optimize clean/test steps
#  - mvn clean install -B -Dintegration_test_settings=`pwd`/test/travis-ci/components-persistence-hsql.properties
  - mvn clean install -B -Dintegration_test_settings=`pwd`/test/travis-ci/components-persistence-mysql.properties
#  - mvn clean install -B -Dintegration_test_settings=`pwd`/test/travis-ci/components-persistence-postgresql.properties
  - mvn verify


notifications:
   email:
    recipients:
      - panagiotisdrakatos@gmail.com
    on_success: change
on_failure: always

cache:
  directories:
    - '$HOME/.m2/repository'
